import { createReadStream } from 'node:fs';
import { mkdir, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';

import { env } from '../../config/env.js';
import { sha256Buffer } from '../../lib/crypto.js';
import { detectImageType } from '../../lib/file-type.js';
import {
  NotFoundError,
  PayloadTooLargeError,
  UnsupportedMediaTypeError,
} from '../../lib/errors.js';

/**
 * Local-disk file storage.
 *
 * Storage layout is entirely server-generated: `<uuid>.<ext>` under a
 * date-sharded directory. The client's filename never influences the path —
 * that is what makes traversal (`../../etc/passwd`) structurally impossible
 * rather than something we have to filter for.
 */

const STORAGE_ROOT = path.resolve(env.STORAGE_DIR);

/**
 * Shard by month so one directory does not accumulate millions of entries,
 * which degrades listing and backup on most filesystems.
 */
function shardFor(date = new Date()) {
  return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}`;
}

function absolutePathFor(storageKey) {
  const resolved = path.resolve(STORAGE_ROOT, storageKey);
  // Defence in depth. Keys are generated by us, but if that ever changes this
  // stops a crafted key escaping the storage root.
  if (!resolved.startsWith(STORAGE_ROOT + path.sep)) {
    throw new NotFoundError('File not found');
  }
  return resolved;
}

/**
 * Persist an uploaded buffer.
 *
 * @param {object} app
 * @param {string} userId
 * @param {{ buffer: Buffer, filename: string }} upload
 */
export async function storeUpload(app, userId, { buffer, filename }) {
  if (buffer.length === 0) throw new UnsupportedMediaTypeError('Uploaded file is empty');
  if (buffer.length > env.MAX_UPLOAD_BYTES) {
    throw new PayloadTooLargeError('Upload exceeds the maximum allowed size');
  }

  // The bytes decide the type — not the header, not the extension.
  const detected = detectImageType(buffer);
  if (!detected) {
    throw new UnsupportedMediaTypeError(
      'Only JPEG, PNG, GIF, and WebP images are accepted',
    );
  }

  const shard = shardFor();
  const storageKey = path.posix.join(shard, `${randomUUID()}.${detected.extension}`);
  const destination = absolutePathFor(storageKey);

  await mkdir(path.dirname(destination), { recursive: true });
  // 0o640: readable by the service user and its group, never world-readable,
  // never executable.
  await writeFile(destination, buffer, { mode: 0o640 });

  try {
    return await app.prisma.fileObject.create({
      data: {
        ownerId: userId,
        storageKey,
        // Kept for display only. Truncated so a pathological name cannot bloat
        // the row, and never used to build a path.
        originalName: String(filename ?? 'upload').slice(0, 255),
        mime: detected.mime,
        sizeBytes: buffer.length,
        sha256: sha256Buffer(buffer),
      },
    });
  } catch (error) {
    // Don't leave an orphaned blob if the metadata write fails.
    await unlink(destination).catch(() => {});
    throw error;
  }
}

/**
 * Look up a file the caller is allowed to read.
 *
 * Files are currently owner-only. Shared visibility (a listing photo visible to
 * every browser of the book exchange) is granted by the modules that reference
 * the file, via `readableFileIds`.
 */
export async function getReadableFile(app, viewerId, id) {
  const file = await app.prisma.fileObject.findUnique({ where: { id } });
  if (!file) throw new NotFoundError('File not found');

  if (file.ownerId === viewerId) return file;

  // Attached to something community-visible? Then any signed-in user may see it.
  const [asBookImage, asLostFoundImage, asAvatar] = await Promise.all([
    app.prisma.bookImage.count({ where: { fileId: id } }),
    app.prisma.lostFoundImage.count({ where: { fileId: id } }),
    app.prisma.user.count({ where: { avatarFileId: id } }),
  ]);

  if (asBookImage + asLostFoundImage + asAvatar > 0) return file;

  // Same 404-not-403 rule as everywhere else.
  throw new NotFoundError('File not found');
}

/** Stream for the download route. */
export function openFileStream(file) {
  return createReadStream(absolutePathFor(file.storageKey));
}

export async function deleteFile(app, userId, id) {
  const file = await app.prisma.fileObject.findFirst({
    where: { id, ownerId: userId },
  });
  if (!file) throw new NotFoundError('File not found');

  await app.prisma.fileObject.delete({ where: { id } });
  // Best-effort: the row is the source of truth, so a failed unlink leaves an
  // orphan blob rather than a dangling reference.
  await unlink(absolutePathFor(file.storageKey)).catch(() => {});
}

export function toFileResponse(file) {
  return {
    id: file.id,
    mime: file.mime,
    sizeBytes: file.sizeBytes,
    originalName: file.originalName,
    createdAt: file.createdAt,
  };
}
